def print_psycopg2_exception(err):
    ...
